name: Auto Tag
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Create tag
        run: |
          VERSION=$(jq -r .version composer.json)
          git tag "v$VERSION"
          git push origin "v$VERSION"